// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	resources "github.com/gardener/gardener-resource-manager/pkg/apis/resources"
	core "github.com/gardener/gardener/pkg/apis/core"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ManagedResource)(nil), (*resources.ManagedResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManagedResource_To_resources_ManagedResource(a.(*ManagedResource), b.(*resources.ManagedResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.ManagedResource)(nil), (*ManagedResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_ManagedResource_To_v1alpha1_ManagedResource(a.(*resources.ManagedResource), b.(*ManagedResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedResourceSpec)(nil), (*resources.ManagedResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec(a.(*ManagedResourceSpec), b.(*resources.ManagedResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.ManagedResourceSpec)(nil), (*ManagedResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec(a.(*resources.ManagedResourceSpec), b.(*ManagedResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedResourceStatus)(nil), (*resources.ManagedResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus(a.(*ManagedResourceStatus), b.(*resources.ManagedResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.ManagedResourceStatus)(nil), (*ManagedResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus(a.(*resources.ManagedResourceStatus), b.(*ManagedResourceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ManagedResource_To_resources_ManagedResource(in *ManagedResource, out *resources.ManagedResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ManagedResource_To_resources_ManagedResource is an autogenerated conversion function.
func Convert_v1alpha1_ManagedResource_To_resources_ManagedResource(in *ManagedResource, out *resources.ManagedResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManagedResource_To_resources_ManagedResource(in, out, s)
}

func autoConvert_resources_ManagedResource_To_v1alpha1_ManagedResource(in *resources.ManagedResource, out *ManagedResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_resources_ManagedResource_To_v1alpha1_ManagedResource is an autogenerated conversion function.
func Convert_resources_ManagedResource_To_v1alpha1_ManagedResource(in *resources.ManagedResource, out *ManagedResource, s conversion.Scope) error {
	return autoConvert_resources_ManagedResource_To_v1alpha1_ManagedResource(in, out, s)
}

func autoConvert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec(in *ManagedResourceSpec, out *resources.ManagedResourceSpec, s conversion.Scope) error {
	out.SecretRefs = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.SecretRefs))
	return nil
}

// Convert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec(in *ManagedResourceSpec, out *resources.ManagedResourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManagedResourceSpec_To_resources_ManagedResourceSpec(in, out, s)
}

func autoConvert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec(in *resources.ManagedResourceSpec, out *ManagedResourceSpec, s conversion.Scope) error {
	out.SecretRefs = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.SecretRefs))
	return nil
}

// Convert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec is an autogenerated conversion function.
func Convert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec(in *resources.ManagedResourceSpec, out *ManagedResourceSpec, s conversion.Scope) error {
	return autoConvert_resources_ManagedResourceSpec_To_v1alpha1_ManagedResourceSpec(in, out, s)
}

func autoConvert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus(in *ManagedResourceStatus, out *resources.ManagedResourceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus(in *ManagedResourceStatus, out *resources.ManagedResourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManagedResourceStatus_To_resources_ManagedResourceStatus(in, out, s)
}

func autoConvert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus(in *resources.ManagedResourceStatus, out *ManagedResourceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus is an autogenerated conversion function.
func Convert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus(in *resources.ManagedResourceStatus, out *ManagedResourceStatus, s conversion.Scope) error {
	return autoConvert_resources_ManagedResourceStatus_To_v1alpha1_ManagedResourceStatus(in, out, s)
}
